'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Sports', [
      {
        name: 'バスケットボール',
        teacher: '佐々木 直基',
        week: 'Monday',
        time: 2,
        first_num: 58106,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '剣道',
        teacher: '天野 聡',
        week: 'Monday',
        time: 2,
        first_num: 58120,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'テニス',
        teacher: '宮崎 靖雄',
        week: 'Monday',
        time: 2,
        first_num: 58134,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '野外スポーツ',
        teacher: '野口 和行',
        week: 'Monday',
        time: 2,
        first_num: 58148,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'バスケットボール',
        teacher: '佐々木 直基',
        week: 'Monday',
        time: 3,
        first_num: 58162,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '野外スポーツ(セミエキスパート)',
        teacher: '野口 和行',
        week: 'Monday',
        time: 3,
        first_num: 58176,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'トレーニング',
        teacher: '吹田 真士',
        week: 'Monday',
        time: 3,
        first_num: 58190,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '剣道',
        teacher: '天野 聡',
        week: 'Monday',
        time: 3,
        first_num: 58204,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'テニス(セミエキスパート)',
        teacher: '宮崎 靖雄',
        week: 'Monday',
        time: 3,
        first_num: 58218,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'クラシックバレエ',
        teacher: '加藤 八重子',
        week: 'Monday',
        time: 3,
        first_num: 58232,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'こころのエクササイズ',
        teacher: '貞安 元',
        week: 'Monday',
        time: 3,
        first_num: 58246,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '気功',
        teacher: '加藤 八重子',
        week: 'Monday',
        time: 4,
        first_num: 58260,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'こころのエクササイズ',
        teacher: '貞安 元',
        week: 'Monday',
        time: 4,
        first_num: 58274,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'バドミントン(セミエキスパート)',
        teacher: '吹田 真士',
        week: 'Monday',
        time: 4,
        first_num: 58288,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'バドミントン',
        teacher: '吹田 真士',
        week: 'Monday',
        time: 5,
        first_num: 58302,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'トランポリン(GIGA)',
        teacher: '水鳥 寿思',
        week: 'Monday',
        time: 5,
        first_num: 58316,
        semester: 20195,
        first_d: 190923,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'アーチェリー(セミエキスパート)',
        teacher: '山本 博',
        week: 'Tuesday',
        time: 2,
        first_num: 58330,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '食事学(食育)',
        teacher: '河谷 彰子',
        week: 'Tuesday',
        time: 2,
        first_num: 58344,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '身体表現技法(セミエキスパート)',
        teacher: '町田 樹',
        week: 'Tuesday',
        time: 2,
        first_num: 58358,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'スポーツ鬼ごっこ',
        teacher: '大崎 恵介',
        week: 'Tuesday',
        time: 2,
        first_num: 58372,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フライングディスク',
        teacher: '大崎 恵介',
        week: 'Tuesday',
        time: 3,
        first_num: 58386,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'アーチェリー',
        teacher: '山本 博',
        week: 'Tuesday',
        time: 3,
        first_num: 58400,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ダンスコンディショニング',
        teacher: '町田 樹',
        week: 'Tuesday',
        time: 3,
        first_num: 58428,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '食事学(アスリートと食事)',
        teacher: '河谷 彰子',
        week: 'Tuesday',
        time: 3,
        first_num: 58414,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ユニバーサルスポーツ',
        teacher: '柳澤 洋介',
        week: 'Tuesday',
        time: 4,
        first_num: 58470,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フェンシング',
        teacher: '澤田 聡',
        week: 'Tuesday',
        time: 4,
        first_num: 58484,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '食事学(健康と食事)',
        teacher: '河谷 彰子',
        week: 'Tuesday',
        time: 4,
        first_num: 58498,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'リズミックトレーニング',
        teacher: '藤井 進也',
        week: 'Tuesday',
        time: 4,
        first_num: 58512,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ユニバーサルスポーツ',
        teacher: '柳澤 洋介',
        week: 'Tuesday',
        time: 5,
        first_num: 58526,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フェンシング',
        teacher: '澤田 聡',
        week: 'Tuesday',
        time: 5,
        first_num: 58540,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フットサル(セミエキスパート)',
        teacher: '小宮山 友祐',
        week: 'Wednesday',
        time: 2,
        first_num: 58556,
        semester: 20195,
        first_d: 190924,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ボディコンディショニング(セミエキスパート)',
        teacher: '大熊 玲子',
        week: 'Wednesday',
        time: 2,
        first_num: 58568,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'レクリエーションスポーツ',
        teacher: '山田 貴子',
        week: 'Wednesday',
        time: 2,
        first_num: 58582,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フットサル',
        teacher: '小宮山 友祐',
        week: 'Wednesday',
        time: 3,
        first_num: 58596,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ピラティス',
        teacher: '大熊 玲子',
        week: 'Wednesday',
        time: 3,
        first_num: 58610,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'アドベンチャーラーニング(セミエキスパート)',
        teacher: '山田 貴子',
        week: 'Wednesday',
        time: 3,
        first_num: 58624,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ヨガ',
        teacher: '加藤 亜希子',
        week: 'Wednesday',
        time: 4,
        first_num: 58638,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フットサル',
        teacher: '小宮山 友祐',
        week: 'Wednesday',
        time: 4,
        first_num: 58652,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'アドベンチャーラーニング(セミエキスパート)',
        teacher: '山田 貴子',
        week: 'Wednesday',
        time: 4,
        first_num: 58666,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'スカッシュ',
        teacher: '山崎 貴行',
        week: 'Wednesday',
        time: 5,
        first_num: 58680,
        semester: 20195,
        first_d: 190925,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '空手',
        teacher: '外薗 大志',
        week: 'Thursday',
        time: 2,
        first_num: 58708,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ソフトボール',
        teacher: '松橋 崇史',
        week: 'Thursday',
        time: 2,
        first_num: 58722,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'リズミックトレーニング(ダンス)',
        teacher: '村田 由香里',
        week: 'Thursday',
        time: 2,
        first_num: 58736,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'GIGA',
        teacher: '森 将輝',
        week: 'Thursday',
        time: 2,
        first_num: 58750,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ジョギング',
        teacher: '永野 智久',
        week: 'Thursday',
        time: 2,
        first_num: 58694,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'レクリエーションスポーツ',
        teacher: '永野 智久',
        week: 'Thursday',
        time: 3,
        first_num: 58764,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ベースボール',
        teacher: '松橋 崇史',
        week: 'Thursday',
        time: 3,
        first_num: 58778,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ボールゲームスポーツ',
        teacher: '岩月 基洋',
        week: 'Thursday',
        time: 3,
        first_num: 58792,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '空手',
        teacher: '外薗　大志',
        week: 'Thursday',
        time: 3,
        first_num: 58806,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'リズミックトレーニング(ダンス)',
        teacher: '村田 由香里',
        week: 'Thursday',
        time: 3,
        first_num: 58820,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ソフトボール',
        teacher: '松橋 崇史',
        week: 'Thursday',
        time: 4,
        first_num: 58834,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'レクリエーションスポーツ',
        teacher: '永野 智久',
        week: 'Thursday',
        time: 4,
        first_num: 58848,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '合氣道',
        teacher: '城 雅昭',
        week: 'Thursday',
        time: 4,
        first_num: 58862,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'リズミックトレーニング(ダンス)',
        teacher: '村田 由香里',
        week: 'Thursday',
        time: 4,
        first_num: 58890,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ソフトバレーボール',
        teacher: '岩月 基洋',
        week: 'Thursday',
        time: 5,
        first_num: 58904,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '合氣道(セミエキスパート)',
        teacher: '城 雅昭',
        week: 'Thursday',
        time: 5,
        first_num: 58918,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'フィットネスプログラム',
        teacher: '永窪 健太',
        week: 'Thursday',
        time: 5,
        first_num: 58932,
        semester: 20195,
        first_d: 190926,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'バスケットボール',
        teacher: '木塚 孝幸',
        week: 'Friday',
        time: 2,
        first_num: 58946,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ゴルフ',
        teacher: '内藤 潔',
        week: 'Friday',
        time: 2,
        first_num: 58960,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '水泳',
        teacher: '鷲見 全弘',
        week: 'Friday',
        time: 2,
        first_num: 58974,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'バスケットボール',
        teacher: '木塚 孝幸',
        week: 'Friday',
        time: 3,
        first_num: 58988,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '水泳',
        teacher: '鷲見 全弘',
        week: 'Friday',
        time: 3,
        first_num: 59002,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ゴルフ',
        teacher: '内藤 潔',
        week: 'Friday',
        time: 3,
        first_num: 59016,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'バレーボール',
        teacher: '宗雲 健司',
        week: 'Friday',
        time: 3,
        first_num: 59030,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'トレーニング',
        teacher: '木塚 孝幸',
        week: 'Friday',
        time: 4,
        first_num: 59044,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ゴルフ',
        teacher: '内藤 潔',
        week: 'Friday',
        time: 4,
        first_num: 59072,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '自律訓練法',
        teacher: '猿渡 めぐみ',
        week: 'Friday',
        time: 4,
        first_num: 59086,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'ボールゲームスポーツ',
        teacher: '山本 耕太',
        week: 'Friday',
        time: 4,
        first_num: 59100,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '自律訓練法(セミエキスパート)',
        teacher: '猿渡 めぐみ',
        week: 'Friday',
        time: 5,
        first_num: 59114,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: '卓球',
        teacher: '山本 耕太',
        week: 'Friday',
        time: 5,
        first_num: 59128,
        semester: 20195,
        first_d: 190927,
        created_at: new Date(),
        updated_at: new Date()
      }
    ], {
      charset: 'utf8',
      collate: 'utf8_unicode_ci'
    });
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Sports', null, {});
  }
};
